dist: trusty
language: cpp
compiler: gcc
sudo: required
script:
 - gcc --version
 - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
 - ./autogen.sh && ./configure && make -j2 && make -j2 check && make lint
before_install: scripts/travis/prepare-ubuntu.sh
install:
 - scripts/travis/install-libunwind.sh
 - scripts/travis/install-spdlog.sh
 - scripts/travis/install-glog.sh
 - scripts/travis/install-gflags.sh
 - scripts/travis/install-double-conversion.sh
 - scripts/travis/install-cctz.sh
 - scripts/travis/install-flatbuffers.sh
 - scripts/travis/install-libevent.sh
 - scripts/travis/install-ucl.sh
after_failure:
 - cat tests/test-suite.log
 - ls -ahl /usr/local/lib
 - env
