package:
  name: roq-api
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}

source:
  path: ..

build:
  skip: True  # [win]
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '0_00000000') }}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - roq-oss-gflags
    - roq-oss-libevent
    - roq-oss-benchmark
    - roq-oss-cctz
    - roq-oss-crossguid
    - roq-oss-flatbuffers
    - roq-oss-libucl
    - roq-oss-libunwind  # [linux]
    - roq-oss-spdlog
  run:
    - roq-oss-gflags
    - roq-oss-libevent
    - roq-oss-benchmark
    - roq-oss-cctz
    - roq-oss-crossguid
    - roq-oss-flatbuffers
    - roq-oss-libucl
    - roq-oss-libunwind  # [linux]
    - roq-oss-spdlog

about:
  home: https://github.com/roq-trading
  dev_url: https://github.com/roq-trading
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://opensource.org/licenses/BSD-3-Clause
  summary: Generic trading API.
  description: Generic trading API.
