{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set number = environ.get('GIT_DESCRIBE_NUMBER', 0) %}

package:
  name: roq-api
  version: {{ version }}

source:
  path: ..

build:
  skip: true  # [win and osx]
  number: {{ number }}
  run_exports:
    strong:
      - {{ pin_subpackage('roq-api', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - doxygen
    - flatbuffers
    - make
  host:
    - fmt
    - roq-oss-span-lite

about:
  home: https://roq-trading.com
  doc_url: https://roq-trading.com/docs
  dev_url: https://github.com/roq-trading
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Roq API
