{% set roq_build="0.2.2" %}
{% set roq_api="0.2.2" %}
{% set benchmark_api="1.4.1" %}
{% set gflags_api="2.2.1" %}
{% set libevent_api="2.1.8" %}
{% set cctz_api="2.2" %}
{% set crossguid_api="0.2.2" %}
{% set flatbuffers_api="1.9.0" %}
{% set libucl_api="0.8.1" %}
{% set libunwind_api="1.2.1" %}
{% set spdlog_api="1.1.0" %}

package:
  name: roq-api
  version: {{ roq_build }}

source:
  path: ../.

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - roq-oss-gflags >={{ gflags_api }}
    - roq-oss-libevent >={{ libevent_api }}
    - roq-oss-benchmark >={{ benchmark_api }}
    - roq-oss-cctz >={{ cctz_api }}
    - roq-oss-crossguid >={{ crossguid_api }}
    - roq-oss-flatbuffers >={{ flatbuffers_api }}
    - roq-oss-libucl >={{ libucl_api }}
    - roq-oss-libunwind >={{ libunwind_api }}  # [linux]
    - roq-oss-spdlog >={{ spdlog_api }}
  run:
    - roq-oss-gflags >={{ gflags_api }}
    - roq-oss-libevent >={{ libevent_api }}
    - roq-oss-benchmark >={{ benchmark_api }}
    - roq-oss-cctz >={{ cctz_api }}
    - roq-oss-crossguid >={{ crossguid_api }}
    - roq-oss-flatbuffers >={{ flatbuffers_api }}
    - roq-oss-libucl >={{ libucl_api }}
    - roq-oss-libunwind >={{ libunwind_api }}  # [linux]
    - roq-oss-spdlog >={{ spdlog_api }}

about:
  home: https://github.com/roq-trading
  dev_url: https://github.com/roq-trading
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://opensource.org/licenses/BSD-3-Clause
  summary: Generic trading API.
  description: Generic trading API.
