{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set number = environ.get('GIT_DESCRIBE_NUMBER', 0) %}

{% set components = version.split('.') %}
{% set major = components[0] | int %}
{% set minor = components[1] | int %}

package:
  name: roq-api
  version: {{ version }}

source:
  path: ..

build:
  skip: True  # [win and osx]
  number: {{ number }}
  run_exports:
    strong:
      - roq-api >={{ version }},<{{ major }}.{{ minor + 1 }}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - gflags >=2.2
    - roq-oss-fmt
    - roq-oss-libunwind  # [linux]
    - roq-oss-spdlog

about:
  home: https://roq-trading.com
  dev_url: https://github.com/roq-trading
  license: Commercial
  license_family: PROPRIETARY
  license_file: LICENSE
  summary: Roq API library
